### ISSUE TITLE
DLL injection to make child processes use fast pipe?

### ISSUE THREAD

**Issue by mcourteaux** [cmuratori/refterm#12]
I'm a Linux person, but I think there is such a thing as DLL injection possible in Windows. I was wondering if you could make all programs use fastpipe by redirecting stdout and stderr by injecting some code that does this.

**Comment by cmuratori** [comment]
You can, but it is hopefully not necessary. fast_pipe.h was for performance verification for the reference renderer. The "correct" solution to this problem long-term is to just use ConPTY to replace the entire terminal conduit, which is possible as of Windows 10 (see https://github.com/jfhs/handterm/ for an example project).

\- Casey
