### ISSUE TITLE
compiling with vs-2022 preview ... don't

### ISSUE THREAD

**Issue by Androthi** [cmuratori/refterm#19]
after wracking my brain for 20 minutes trying to figure out why the damn user32 library (?? and perhaps some others) wasn't linking i switched over to the stable vs-2019 and problem solved.

i don't know if it's a bug with 2022 or some missing files. i know most of the libraries used in this project are in there, i've been able to compile other things requiring requiring them, but for some reason this doesn't.

**Comment by cmuratori** [comment]
Maybe you should file a bug report in the MS repo?

Just kidding!

Can you post the link errors you're getting?  That might help narrow down what's wrong with Microsoft's latest masterpiece.

\- Casey

**Comment by Androthi** [comment]
honestly, i don't know if it's worth it, but here it is for anyone interested. i get a bunch of strange warnings then linkage errors. the warnings might be a clue, but with my limited knowledge, i don't see anything with the code that should be producing those warnings, so i'm going to assume something is wrong or different in vs-2022 header files.


c:\Dev\Workspace\REPOS\refterm-main>build
compilation header save succeeded; see c:\Dev\Workspace\REPOS\refterm-main\refterm_cs.h
compilation header save succeeded; see c:\Dev\Workspace\REPOS\refterm-main\refterm_ps.h
compilation header save succeeded; see c:\Dev\Workspace\REPOS\refterm-main\refterm_vs.h
refterm.c
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(22): warning C4293: '>>': shift count negative or too big, undefined behavior
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(172): warning C4013: '_mm_cvtsi64_si128' undefined; assuming extern returning int
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(172): error C2440: 'initializing': cannot convert from 'int' to '__m128i'
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c(86): warning C4018: '<': signed/unsigned mismatch
Generating Code...
Compiling...
refterm_example_dwrite.cpp
Generating Code...
refterm.c
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(22): warning C4293: '>>': shift count negative or too big, undefined behavior
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(172): warning C4013: '_mm_cvtsi64_si128' undefined; assuming extern returning int
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_source_buffer.c(172): error C2440: 'initializing': cannot convert from 'int' to '__m128i'
c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c(86): warning C4018: '<': signed/unsigned mismatch
Generating Code...
Compiling...
refterm_example_dwrite.cpp
Generating Code...
lld-link: error: undefined symbol: __declspec(dllimport) CreateThread
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) GetMessageW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:129
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) TranslateMessage
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:130
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) PostThreadMessageA
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:135
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) DispatchMessageW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:139
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) VirtualAlloc
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:976
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1007
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:817
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(RefreshFont)
>>> referenced 1 more times

lld-link: error: undefined symbol: ScriptRecordDigitSubstitution
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1003
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: ScriptApplyDigitSubstitution
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1004
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) wsprintfW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1009
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1205
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:742
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(ExecuteSubProcess)

lld-link: error: undefined symbol: __declspec(dllimport) ShowWindow
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1013
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) QueryPerformanceFrequency
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1027
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) QueryPerformanceCounter
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1028
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1031
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1177
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)
>>> referenced 1 more times

lld-link: error: undefined symbol: __declspec(dllimport) PeekMessageA
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1042
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) WideCharToMultiByte
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1131
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) GetClientRect
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1144
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) SetWindowTextW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1209
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) ExitProcess
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1220
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) LoadLibraryW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:70
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(PreventWindowsDPIScaling)

lld-link: error: undefined symbol: __declspec(dllimport) GetProcAddress
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:71
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(PreventWindowsDPIScaling)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:78
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(PreventWindowsDPIScaling)

lld-link: error: undefined symbol: __declspec(dllimport) GetModuleHandleW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:88
>>>               C:\Users\dev\AppData\Local\Temp\refterm-1cf888.o:(CreateOutputWindow)

lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
lld-link: error: undefined symbol: __declspec(dllimport) LoadLibraryW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:118
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) GetProcAddress
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:118
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:118
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) GetModuleHandleW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) LoadIconA
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) LoadCursorA
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) GetStockObject
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) RegisterClassExW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) CreateWindowExW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:120
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) CreateThread
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) GetMessageW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) TranslateMessage
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) PostThreadMessageA
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) DispatchMessageW
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm.c:124
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(WinMainCRTStartup)

lld-link: error: undefined symbol: __declspec(dllimport) VirtualAlloc
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:976
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1007
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1163
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)
>>> referenced 1 more times

lld-link: error: undefined symbol: IID_IDXGISurface
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:998
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) CreateCompatibleDC
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1000
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) CreateDIBSection
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1000
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) SelectObject
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1000
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:795
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(RefreshFont)
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:795
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(RefreshFont)

lld-link: error: undefined symbol: __declspec(dllimport) SetTextColor
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1000
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)

lld-link: error: undefined symbol: __declspec(dllimport) SetBkColor
>>> referenced by c:\Dev\Workspace\REPOS\refterm-main\refterm_example_terminal.c:1000
>>>               C:\Users\dev\AppData\Local\Temp\refterm-787794.o:(TerminalThread)

lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
splat.cpp
splat2.cpp

**Comment by mmozeiko** [comment]
You are building 32-bit binary. It is not really supported, code expects 64-bit target. You should run build.bat from VS 64-bit command prompt.

**Comment by Androthi** [comment]
Was it as easy as that? Lol. The install just gave me one cli link, I didn't know 32 bit was still supported. I'll have to check that when I get home.

**Comment by mmozeiko** [comment]
Not installer. The command-prompt. If you're running vcvarsall.bat file yourself, then append `amd64` argument. That's the same as you do for VS2019 or any earlier version. If you launch command-prompt version, select correct shortcut - the one with `x64 Native Tools` in the name.

**Comment by cmuratori** [comment]
Maybe we should put a #error in the code so if you try to compile 32-bit it tells you to compile 64-bit, so at least people know?

\- Casey

**Comment by mmozeiko** [comment]
Yeah either in code, or in build.bat file:

    if "%Platform%" neq "x64" (
        echo ERROR: please run this from MSVC command prompt for 64-bit compiler
        exit /b 1
    )

**Comment by zalo** [comment]
For what it's worth, I found the appropriate VS 2022 x64 prompt at:
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2022\Visual Studio Tools\VC\` as `x64 Native Tools Command Prompt for VS 2022 Preview` (which seems to be a different location than where prior Visual Studios had it?)

Using this I'm able to build refterm and splat [the big list of naughty strings](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt) no problem.

**Comment by Androthi** [comment]
I will probably be the only idiot trying to compile in 32 bits. The thought
that I might be using the 32 bit compiler never crossed my mind. The shift
error should have been the clue now that I think about it. Lol.

**Comment by cmuratori** [comment]
This should be fixed in the 60e3eaf784098ba1f844e5599c359a3b727ddb5e commit.  The only remaining issue is that clang still "compiles" but just doesn't link if you try to compile in x86 shell directly, but that is probably a minor case. There are checks in the batch file directly, so if you're using the batch, you should get a clean error if you're set up for 32-bit builds instead of 64-bit.

\- Casey
