### ISSUE TITLE
Doesn't work on my grandma's macbook

### ISSUE THREAD

**Issue by Phrasing** [cmuratori/refterm#2]
In the metaphysics of identity, the ship of Theseus is a thought experiment that raises the question of whether an object that has had all of its components replaced remains fundamentally the same object. The concept is one of the oldest in Western philosophy, having been discussed by Heraclitus and Plato by c. 500–400 BC.

The thought puzzle was discussed by ancient philosophers such as Heraclitus (Cratylus 401d) and Plato (Parmenides 139),[1] later by Plutarch,[2] and more recently by Thomas Hobbes and John Locke. Several variants are known, including the grandfather's axe, which has had both head and handle replaced. The puzzle itself is an example of Ship of Theseus, as the original story has had various elements replaced over time.

The particular "ship of Theseus" version of the thought puzzle was first introduced in Greek legend as reported by the historian, biographer, and essayist Plutarch:

The ship wherein Theseus and the youth of Athens returned from Crete had thirty oars, and was preserved by the Athenians down even to the time of Demetrius Phalereus, for they took away the old planks as they decayed, putting in new and stronger timber in their places, insomuch that this ship became a standing example among the philosophers, for the logical question of things that grow; one side holding that the ship remained the same, and the other contending that it was not the same.

### — Plutarch, Theseus[2]
Plutarch thus questions whether the ship would remain the same if it were entirely replaced, piece by piece. Centuries later, the philosopher Thomas Hobbes introduced a further puzzle, wondering what would happen if the original planks were gathered up after they were replaced, and then used to build a second ship.[3] Hobbes asked which ship, if either, would be the original ship of Theseus.

An ancient Buddhist text titled in Sanskrit Mahāprajñāpāramitopadeśa, which was later translated into Classical Chinese (Da zhidu lun 大智度論), contains a similar philosophical puzzle. It takes the form of a body-swapping story. The story tells of a traveler who encountered two demons in the night. As one demon ripped off all parts of his body one by one, the other demon replaced them with those of a corpse. The traveler was left confused about who he was after the body-swapping.[4]

**Comment by cmuratori** [comment]
Spam.

\- Casey
