### ISSUE TITLE
Infinite loop in ParseLineIntoGlyphs

### ISSUE THREAD

**Issue by mrylmz** [cmuratori/refterm#22]
Using the following sequence of binary data it is possible to cause an infinite loop when `Peek = '\x1b'` and `ContainsComplexChars = true`

```hex
F2 1B
```

**Comment by cmuratori** [comment]
Just want to double-check: is that with the current codebase, or an earlier revision?  (But thank you for the report either way!)

\- Casey

**Comment by mrylmz** [comment]
Sorry didn't recheck the upstream for updates, is working fine in the latest version. 

This was happening in commit `1ac2e1f`.

**Comment by cmuratori** [comment]
Awesome, thanks for verifying.  Let me know if you find any others like this!

\- Casey
