### ISSUE TITLE
This is so ridiculous. fast_io + refterm outperforms stdio.h + cmd for 291 times

### ISSUE THREAD

**Issue by expnkx** [cmuratori/refterm#23]
![image](https://user-images.githubusercontent.com/57303909/124845839-90440580-df65-11eb-89bf-baa94a7f9f12.png)

Please continue working on this project to kick microsoft's ass. Also ignore shit like W apis so we can correct all the mistakes and braindeath Microsoft created.

```cpp
#include<fast_io.h>
#include<fast_io_driver/timer.h>

int main()
{
	fast_io::timer tm(u8"tm");
	{
	auto obf{fast_io::out_buf()};
	for(std::size_t i{};i!=1000000;++i)
		println(obf,i);
	}
}
//0.875684s
```

```
#include<fast_io.h>
#include<fast_io_driver/timer.h>

int main()
{
	fast_io::timer tm(u8"tm");
	{
	for(std::size_t i{};i!=1000000;++i)
		printf("%zu\n",i);
	}
}
//254.8527817s
```

**Comment by cmuratori** [comment]
I'm not sure there's much left to demonstrate with this project, to be honest.  Oversized glyphs is one thing, and some more VT parsing, etc.  But, pretty much everything's there for anyone who wants to make a terminal :)

\- Casey

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/124851593-d783c380-df70-11eb-8294-59290b7c080a.png)
Thank you!!! i tried fastpipe. LOL 
58049x faster. Truly disaster
