### ISSUE TITLE
What is the purpose of a custom implementation of `memset` and `memcpy`?

### ISSUE THREAD

**Issue by cculianu** [cmuratori/refterm#28]
Referring to here: https://github.com/cmuratori/refterm/blob/60e3eaf784098ba1f844e5599c359a3b727ddb5e/refterm.c#L161

There are several problems with this:

1. A C compiler may elide your calls to your custom `memset` and `memcpy` anyway and use in-line code that is optimized.
2. The implementation provided is likely slower than the C library one anyway.
3. I am not even sure you can legally do this in a C program as per the standard (that is, those function names may be reserved -- I'm not actually sure about this one tbh)

What is the purpose of re-implementing these functions?  This looks like a code smell to me.. I am sad to say.   I recommend the codebase switch to just using the standard `memset`/`memcpy` provided by the C library.

**Comment by mmozeiko** [comment]
1. That would be actually preferable - to have all the places inlined, so there is no dependency on external code. Unfortunately completely opposite happens (at least with MSVC) - it transforms simple loops or zero initializations to calls to memcpy and memset - that's why they need to be explicitly defined when you do not link to C runtime. If you know a way to avoid this, please share the information

2. That is pretty irrelevant, as the way these functions are used in code are only in performance non-critical places. In case performance is critical, custom code is/will be written anyway.

The main purpose of this is to reimplement these functions is to avoid linking to C runtime, because I said above - compiler implicitly inserts calls to them.

**Comment by cculianu** [comment]
1. Hmm. Strange. I use clang mainly on macOS (but I am no alien to the C runtime on windows).  On my compile the compiler mainly AVOIDS calling `memset` and/or `memcpy`.  Are you sure this happens with optimizations enabled (e.g. `/O3` )?  It would be very surprising if MSVC did this.  MSVC's optimizer is pretty good.  I question whether this is true, but don't have time right now to play with godbolt to look at the asm.  I'm pretty sure that with optimizations enabled .. 9 times out of 10 it should actually inject inline asm code and *not* call those functions....
2. Oh, if you wanted to avoid linking to the C runtime?  I keep forgetting that on windows that's a thing people want to avoid. In that case then this is fine.... if it buys you that -- it has some justification! Carry on then...

**Comment by cculianu** [comment]
Update: yes -- indeed MSVC never elides the calls to `memset` and `memcpy` even with `/O3`, whereas both `gcc` and `clang` do in some cases.  Interesting. :/

**Comment by mmozeiko** [comment]
It's not about eliding existing calls. It's about MSVC inserting new calls where there were no calls before.
Like `BigStruct s = { 0 };` - MSVC will do memset for this if struct is large enough. Instead for rep stosb or similar code.

**Comment by cculianu** [comment]
Really! Wow. That's.. gross.  :)

gcc and/or clang never do this AFAICT.

They even elide `memset` and `memcpy` for you often, [see here](https://godbolt.org/#z:OYLghAFBqRAWIDGB7AJgUwKKoJYBdkAnAGhxAgDNkA7PAZUQEMAbdEARgBZiraBVAM7oACgA8QAcgAME4gCsQAJmLNG1UAH0tiYkNaI8OGuXTVUAYWTMArgFtqS4qdQAZHNXQA5OwCN0hDiliAAdkAXwjaksbe0dQ8MMaNw9vWz8A9iC9dANIujxGQjxouwdlbNyafMK8ZK9ff0DdAqKS2PKW2vd6tMbMgEpdZGtCRDYJAHoJgGoAFQBPYPRp%2BeHCaZQMabh/dGJpomnmZEZUabVp9FFGW2DWADoAUikAQUfFAGZ3RBstx4/zAI8LhaPc4P9MM83p9vr9lv9AXhCO5gGCIVCoQA3ZA4M5CPAaAgadgQbG46YAKh81go/WmjwA7AAhKHTNnTWzoWz4iDUij7dj7RQAVgAbP1/kz2fTXoyACJYnFnFDBeakpWUjBA/YoahA6Zks4UgSjOmMlmvaWc2yIVUQLV4fYmnTTD6KCUfC1vBlyiSDZiSYWyBzSWTISTmaYCNZjemfRSyPCSGSDeBIZC3HCsEhkCAoTPZpDAdglnhZvD%2BATkHzJ2Q%2BdyFeaSdiyfOc2gAeWozCboeIGFsamArFr/ZwhByhkx6CrfauOWsFebsncFYDfeYOB8hEblgwo6ROFsy8GvHoTBHXB4NDwghE4j7CkFqnUIC0Gh0m58Vcgg2QwUSPVJAAWg7D5ZAqQCTDMNoHEFZw6lSdIOBCMIIhoWCUPidDqEQhoMl0dB9EA6pWisUoUMgvJOjw3oCKBGpMMFBiilo5D2EGaMRjGJR/UDYNR3DCRRAADlFYDRU4aZgEQRBphLe52GmCBsHwQ53jdfZLALfw4w%2BDjpnMRNa1TBB82CLN/FIchzMsgJZJfYtFCkQUKHLStq1HetqEbZdiDbUw8C7HtRwHIcRz7XAJ1yadZxkJxRAXJcJBbUhaCI0cvx3Qh5j3cZ4sPY8Ur9a9aAYFg2CvM87zEUcFGURy320FQtx/CA/wAyJZ1A8DCOIyJoIscjYngsw2L6VCEkiJjJpw8b6KIydqMY4a4L6paqho7okImljilWyitpSfCOE4mM2HdFR%2BOIEN4qE0TxMkjZHPkxR7ikRTlNUgh1g05RDIzCzsz091DOM0NTPTHScxswG7KQH52AATg0Zz2GFDRrA%2BDRNLc5gK0IKteS8hscr8gLO27Xt4rC9QIpp8clti0d50QRdxlS1cMo3LdstytB8sTZEipbU8b3Ky9uGqoRasfEAPhUIcmo/Frv3AdriH/QCqwmMD1sqBwIGcTDRQVhDtpO9HZsAk2FewwD5o4YV9ZIzpbZd5bWItuineaFaYgcU2/a946ffRs7uIuviJCDG7BMkB6OQETE5MxZH3uUgB1ABJTxMDpFTcB%2BkGtLh4GNI%2BOkjOIJMIcGABrQIgnXTgBL7ISIPlmuTMGadCYGzggA%3D).

Ok, well.. closing issue. Thanks for the clarification here. TIL.

**Comment by mmozeiko** [comment]
Your godbolt has mistake for MSVC - it does not have `/O3` option - check the output of compiler:

    cl : Command line warning D9002 : ignoring unknown option '/O3'

Max level it has is `/O2`. But even with O2 this happens: https://godbolt.org/z/qb53nKqex
Similarly for memcpy.

**Comment by cculianu** [comment]
Ah right. I tried it also in C mode (link was C++ mode).  Same same. As an aside, I'm curious why MSVC team decided on this. I wonder if they prioritize code size over branch prediction/pipelining speed? Or maybe in their tests most of this time this is better on average?  Strange indeed... I never would have expected this behavior.  

Today I learned!  Thanks for the follow-up.
