### ISSUE TITLE
Default font `Cascadia Mono` is not installed by default on Win10

### ISSUE THREAD

**Issue by cculianu** [cmuratori/refterm#30]
I suggest making the font `Consolas` or somesuch. Cascadia mono doesn't exist on a default Windows 10 system.

**Comment by cmuratori** [comment]
It is set this way at the moment because that appears to be what Windows Terminal uses by default, so comparison is easier:

https://github.com/microsoft/terminal/issues/9375

I will take a look at adding a fallback, though, in case it is not found.

\- Casey

**Comment by cculianu** [comment]
Ah, ok. Thanks.
