### ISSUE TITLE
ComputeGlyphHash for glyph runs longer than 15 bytes

### ISSUE THREAD

**Issue by ltlollo** [cmuratori/refterm#38]
https://github.com/cmuratori/refterm/blob/60e3eaf784098ba1f844e5599c359a3b727ddb5e/refterm_example_source_buffer.c#L193-L202

It seems to me that this loop it's reshaing always the same chunks. Shouldn't there be an `At += 16;` somewere in that loop?

**Comment by cmuratori** [comment]
I added the missing At += 16, but, this code is still untested, so... there is that :)  At some point someone should probably write a unit test against the hash and do some verification, but until then, this is at least "more likely to be correct if it is ever actually called".

\- Casey
