### ISSUE TITLE
Duplicate glyph bug?

### ISSUE THREAD

**Issue by ChristopherDrum** [cmuratori/refterm#44]
I looked through the closed issues and didn't notice anything specifically mentioning this, but it may have been fixed as the result of other bugs. I'll try to find some time later to re-verify this myself on my Windows box, but for now...

I was watching "How fast should an unoptimized terminal run?" and at the end `termbench` is used to show colored glyph rendering performance. I noticed that in refterm, with fast-pipes turned ON, there is a case of a repeated glyph (the letter `b`) that I don't otherwise see as I scrub through the video. (visible when Casey stops the fast-pipe run at 48:56)

![Screen Shot 2021-12-07 at 10 44 25 AM](https://user-images.githubusercontent.com/320377/144952040-b9f48aca-549a-4bfb-8e9b-80123c69278b.png)

Whether this is a bug in `termbench` or in `refterm`, I dunno.

**Comment by mmozeiko** [comment]
My guess is that  this is simply because output was paused when 3rd line from your screenshot was printing out `uvwxyab` and then it stopped, but previous content is still there - continuing on same line with `bcdef...` (same as new row above it)

**Comment by ChristopherDrum** [comment]
I'm dumb.
