### ISSUE TITLE
Crash when entering too many characters into the command line

### ISSUE THREAD

**Issue by Drainyard** [cmuratori/refterm#8]
I discovered a crash when entering 136 or more characters into the command line.
There are no real steps to reproduction, just boot up the terminal, enter 136 characters and press enter.

**Comment by cmuratori** [comment]
This is (almost certainly) just that the command line was just thrown in there and isn't meant to be used :)  Nobody checks the end of the buffer for the cursor.  I can just add a check and that should fix this.

\- Casey

**Comment by cmuratori** [comment]
Should be fixed in the latest push - all I did was just add a guard to the command line so you can't write off the end of the buffer, and made sure the wsprintf garbage that I have to do to call CreateProcess has enough room.  Do you want to check to see if it "fixes" the problem for you?

\- Casey

**Comment by Drainyard** [comment]
I can see you already closed the issue.
I didn't get around to it in the weekend, but I just tested it now and it is fixed for me.
